services:
  mysql:
    image: mysql:8.0
    container_name: teste
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: example_db
      MYSQL_USER: Vt
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: